[package]
name = "bmidi-play"
version = "0.0.1"
authors = ["Benedikt Reinartz <filmor@gmail.com>"]

[dependencies]
bmidi = "0.0.2"
synth = "0.11"
time_calc = "0.11"
clap = "2.32"
cpal = "0.8.2"
dsp-chain = "0.13.1"
futures = "0.1.24"
crossbeam = "0.4.1"
